#
# YAML-formatted (http://www.yaml.org/) build instructions for continuous
# integration via Travis CI (http://docs.travis-ci.com/).
#

notifications:
    email: false

language: c

compiler:
    - gcc

env:
    matrix:
        # Linux x86
        - OS_ID=0.4.4
        # Linux x64
        - OS_ID=0.4.40

before_install:
    - sudo apt-get update

install:
    # gcc-multilib:
    #   For building 32b binaries on a 64b host (not necessary when we build
    #   for 64b).
    # valgrind:
    #   For basic sanity checking of our freshly built binaries.
    # libc6:i386:
    #   For running the 32b bootsrap rebol ("r3-make") on a 64b host.
    # libc6-dbg:i386:
    #   For running valgrind on a 32b subject-under-test on a 64b host.
    - sudo apt-get install -y gcc-multilib valgrind libc6:i386 libc6-dbg:i386
    # Fetch a Rebol bootsrap binary, which is needed for building Rebol.
    - wget http://www.rebol.com/r3/downloads/r3-a111-4-2.tar.gz
    - tar xvzf r3-a111-4-2.tar.gz
    - cp r3 make/r3-make

script:
    - cd make/
    - make make OS_ID=${OS_ID}
    - make clean prep r3
    - valgrind --error-exitcode=42 --leak-check=full ./r3 --do 'print {Hello!}'
